# Natania's Data

## Load data

In [46]:
import pandas as pd
# read my local data
df = pd.read_excel(r'C:\Users\16468\Desktop\STROKE literatures\Natania\nb_all.xlsx')

In [47]:
df.head()

b 1  b 2  fist 1  fist 2  index 1  index 2  pinch 1  pinch 2  three 1  \
0    0    0       0       0        0        0       20       10       20   
1   20    5      15       5       15        0       20       10       20   
2   20    5      20      10       15        0       20        5       20   
3   20    5      20       5       15        0       20        5       20   
4   20    5      20      10       15        0       20        5       20   

   three 2  ...  26 1  26 2  29 1  29 2  35 1  35 2  37 1  37 2  38 1  38 2  
0        0  ...     0     0     0    15     5     5    10     0    20     1  
1        0  ...    20    15    20     0    20     5    20    10    15     5  
2        5  ...    20    15    15     0    15     5    20    10    15     0  
3        0  ...    20    15    20     5    15     0    20    10    15     5  
4        0  ...    25    15    20     0    20     5    20    10    20     5  

[5 rows x 30 columns]

In [48]:
#get the data for first trial
df1=df.iloc[229:660,:]

In [49]:
df1.head()

b 1  b 2  fist 1  fist 2  index 1  index 2  pinch 1  pinch 2  three 1  \
229   15    0      15      20       25       10       10       20       20   
230   15    0      10      20       25       10        5       30       20   
231   15    0      20      25       20        5       15       40       15   
232   15    5      25      30       25        5       10       40       15   
233   15    5      20      25       25        5       10       20       15   

     three 2  ...  26 1  26 2  29 1  29 2  35 1  35 2  37 1  37 2  38 1  38 2  
229        5  ...     0    25    15    10    10     5    25    10    20     5  
230        5  ...     5    30    10     5     5     0    25    10    15     0  
231        5  ...    10    20     0    10     5     0    20    10    25     0  
232        5  ...    15    15    10     5     5     5    15     5    20     0  
233        5  ...    20    10    20     0     0    15    10     0    30     5  

[5 rows x 30 columns]

## Regression Senario 1 (two channels are independent)
Alphabetic gestures channel 1 (x11 to x15)------> Grasp 18 channel 1 (y1)<br>
Alphabetic gestures channel 2 (x21 to x25)------> Grasp 18 channel 2 (y2)

In [50]:
import numpy as np
from sklearn.linear_model import LinearRegression

In [51]:
# get the x and y
x1=df1[['b 1','fist 1','index 1','pinch 1','three 1']]
x2=df1[['b 2','fist 2','index 2','pinch 2','three 2']]
y1=df1['18 1']
y2=df1['18 2']

In [52]:
# fit regression line
reg1 = LinearRegression().fit(x1, y1)
reg2 = LinearRegression().fit(x2, y2)

In [54]:
# intercept of the regression line of x1,y1
print(reg1.intercept_)
# intercept of the regression line of x2,y2
print(reg2.intercept_)

6.378991429693933
6.114586310043276


In [55]:
# coefficient of y1=f(x1)
print(reg1.coef_)
# coefficient of y2=g(x2)
print(reg2.coef_)

[ 0.76755046 -0.00801205 -0.42026     0.34244458 -0.07282228]
[-0.00078889 -0.10447702  0.47847506 -0.06323085 -0.04914328]


## Regression Senario 2 (Multioutput regression)
Alphabetic gestures channel 1 (x1 to x10)------> Grasp 18 channel 1 (y1) AND Alphabetic gestures channel 2 (x1 to x10)------> Grasp 18 channel 2 (y2)<br>
Get (y1, y2)

In [56]:
from sklearn.datasets import make_regression
from sklearn.model_selection import train_test_split
from sklearn.multioutput import MultiOutputRegressor

In [59]:
# get variables
y=df1[['18 1','18 2']]
X=df1[['b 1','fist 1','index 1','pinch 1','three 1','b 2','fist 2','index 2','pinch 2','three 2']]

In [60]:
# Set the model and fit
model = LinearRegression()

In [61]:
model.fit(X, y)

LinearRegression()

In [62]:
# get the coefficient of multioutput model
model.coef_

array([[ 0.73588249, -0.06382268, -0.684659  ,  0.17694457, -0.02801451,
         0.11343114,  0.05340338,  0.6139726 ,  0.32085469, -0.0117054 ],
       [ 0.42592277,  0.01215313, -0.12400416,  0.0877766 ,  0.03086941,
        -0.02070525, -0.08441255,  0.45244542, -0.03806123, -0.03722224]])