# Natania's Data

## Load data

In [46]:
import pandas as pd
# read my local data
df = pd.read_excel(r'C:\Users\16468\Desktop\STROKE literatures\Natania\nb_all.xlsx')

In [47]:
df.head()

b 1  b 2  fist 1  fist 2  index 1  index 2  pinch 1  pinch 2  three 1  \
0    0    0       0       0        0        0       20       10       20   
1   20    5      15       5       15        0       20       10       20   
2   20    5      20      10       15        0       20        5       20   
3   20    5      20       5       15        0       20        5       20   
4   20    5      20      10       15        0       20        5       20   

   three 2  ...  26 1  26 2  29 1  29 2  35 1  35 2  37 1  37 2  38 1  38 2  
0        0  ...     0     0     0    15     5     5    10     0    20     1  
1        0  ...    20    15    20     0    20     5    20    10    15     5  
2        5  ...    20    15    15     0    15     5    20    10    15     0  
3        0  ...    20    15    20     5    15     0    20    10    15     5  
4        0  ...    25    15    20     0    20     5    20    10    20     5  

[5 rows x 30 columns]

In [48]:
#get the data for first trial
df1=df.iloc[229:660,:]

In [49]:
df1.head()

b 1  b 2  fist 1  fist 2  index 1  index 2  pinch 1  pinch 2  three 1  \
229   15    0      15      20       25       10       10       20       20   
230   15    0      10      20       25       10        5       30       20   
231   15    0      20      25       20        5       15       40       15   
232   15    5      25      30       25        5       10       40       15   
233   15    5      20      25       25        5       10       20       15   

     three 2  ...  26 1  26 2  29 1  29 2  35 1  35 2  37 1  37 2  38 1  38 2  
229        5  ...     0    25    15    10    10     5    25    10    20     5  
230        5  ...     5    30    10     5     5     0    25    10    15     0  
231        5  ...    10    20     0    10     5     0    20    10    25     0  
232        5  ...    15    15    10     5     5     5    15     5    20     0  
233        5  ...    20    10    20     0     0    15    10     0    30     5  

[5 rows x 30 columns]

## Regression Senario 1 (two channels are independent)
Alphabetic gestures channel 1 (x11 to x15)------> Grasp 18 channel 1 (y1)<br>
Alphabetic gestures channel 2 (x21 to x25)------> Grasp 18 channel 2 (y2)

In [50]:
import numpy as np
from sklearn.linear_model import LinearRegression

In [51]:
# get the x and y
x1=df1[['b 1','fist 1','index 1','pinch 1','three 1']]
x2=df1[['b 2','fist 2','index 2','pinch 2','three 2']]
y1=df1['18 1']
y2=df1['18 2']

In [52]:
# fit regression line
reg1 = LinearRegression().fit(x1, y1)
reg2 = LinearRegression().fit(x2, y2)

In [54]:
# intercept of the regression line of x1,y1
print(reg1.intercept_)
# intercept of the regression line of x2,y2
print(reg2.intercept_)

6.378991429693933
6.114586310043276


In [55]:
# coefficient of y1=f(x1)
print(reg1.coef_)
# coefficient of y2=g(x2)
print(reg2.coef_)

[ 0.76755046 -0.00801205 -0.42026     0.34244458 -0.07282228]
[-0.00078889 -0.10447702  0.47847506 -0.06323085 -0.04914328]


## Regression Senario 2 (Multioutput regression)
Alphabetic gestures channel 1 (x1 to x10)------> Grasp 18 channel 1 (y1) AND Alphabetic gestures channel 2 (x1 to x10)------> Grasp 18 channel 2 (y2)<br>
Get (y1, y2)

In [56]:
from sklearn.datasets import make_regression
from sklearn.model_selection import train_test_split
from sklearn.multioutput import MultiOutputRegressor

In [59]:
# get variables
y=df1[['18 1','18 2']]
X=df1[['b 1','fist 1','index 1','pinch 1','three 1','b 2','fist 2','index 2','pinch 2','three 2']]

In [60]:
# Set the model and fit
model = LinearRegression()

In [61]:
model.fit(X, y)

LinearRegression()

In [62]:
# get the coefficient of multioutput model
model.coef_

array([[ 0.73588249, -0.06382268, -0.684659  ,  0.17694457, -0.02801451,
         0.11343114,  0.05340338,  0.6139726 ,  0.32085469, -0.0117054 ],
       [ 0.42592277,  0.01215313, -0.12400416,  0.0877766 ,  0.03086941,
        -0.02070525, -0.08441255,  0.45244542, -0.03806123, -0.03722224]])

## 03/28 40 trials ( 10 grasps x 4 trials/grasp) 

In [89]:
import numpy as np
from sklearn.linear_model import LinearRegression

In [90]:
#get the data for trial
df1=df.iloc[229:660,:]
df2=df.iloc[869:1250,:]
df3=df.iloc[1459:1890,:]
df4=df.iloc[2079:2540,:]

In [91]:
trials=[df1,df2,df3,df4]

In [96]:
weights=[]

for i in range(4):
    # five alphabet
    b=pd.concat([trials[i]['b 1'], trials[i]['b 2']], axis=0)
    fist=pd.concat([trials[i]['fist 1'], trials[i]['fist 2']], axis=0)
    index=pd.concat([trials[i]['index 1'], trials[i]['index 2']], axis=0)
    pinch=pd.concat([trials[i]['pinch 1'], trials[i]['pinch 2']], axis=0)
    three=pd.concat([trials[i]['three 1'], trials[i]['three 2']], axis=0)

    xdf=pd.concat([b, fist,index,pinch,three], axis=1)
    
    # 10 grasps
    bottle=pd.concat([trials[i]['18 1'], trials[i]['18 2']], axis=0)
    tube=pd.concat([trials[i]['19 1'], trials[i]['19 2']], axis=0)
    cup=pd.concat([trials[i]['20 1'], trials[i]['20 2']], axis=0)
    knife=pd.concat([trials[i]['21 1'], trials[i]['21 2']], axis=0)
    stick=pd.concat([trials[i]['25 1'], trials[i]['25 2']], axis=0)
    pen=pd.concat([trials[i]['26 1'], trials[i]['26 2']], axis=0)
    ball=pd.concat([trials[i]['29 1'], trials[i]['29 2']], axis=0)
    book=pd.concat([trials[i]['35 1'], trials[i]['35 2']], axis=0)
    disc=pd.concat([trials[i]['37 1'], trials[i]['37 2']], axis=0)
    cap=pd.concat([trials[i]['38 1'], trials[i]['38 2']], axis=0)
    
    grasps=[bottle,tube,cup,knife,stick,pen,ball,book,disc,cap]
    
    for j in range(10):
        regressor=LinearRegression().fit(xdf, grasps[j])
        
        weights.append(regressor.coef_.tolist())

In [99]:
pd.DataFrame(np.array(weights)).to_csv((r'C:\Users\16468\Desktop\STROKE literatures\Natania\weights.csv'))

In [104]:
dfweight=pd.read_csv(r'C:\Users\16468\Desktop\STROKE literatures\Natania\weights.csv')
dfweight

Trial  Grasp        w1        w2        w3        w4        w5
0       1      1  0.034047 -0.160269  0.411626  0.247514 -0.029814
1       1      2 -0.039016 -0.018411  0.224964  0.181373 -0.020624
2       1      3 -0.082686 -0.039937  0.359462  0.229491  0.023193
3       1      4  0.132913 -0.012426  0.310913  0.248484  0.035166
4       1      5  0.040928 -0.034412  0.163945  0.330901 -0.075283
5       1      6  0.066134  0.046846  0.175537  0.330071  0.042722
6       1      7  0.032115 -0.018156  0.251979  0.275781 -0.047760
7       1      8 -0.005871 -0.096659  0.452714 -0.061567 -0.077858
8       1      9  0.104607 -0.031411  0.193538  0.373602  0.100487
9       1     10  0.146211 -0.031257  0.332254  0.102067  0.049892
10      2      1  0.324262 -0.041984  0.003928  0.104656  0.423227
11      2      2  0.215215  0.039583  0.363777  0.110901  0.111815
12      2      3 -0.054706 -0.015721  0.078141  0.413323  0.247481
13      2      4 -0.081251 -0.017134  0.109289  0.481493  0.145223
14      2      5 -0.095259 -0.054981  0.168736  0.107870  0.210608
15      2      6  0.369792 -0.016985  0.135465  0.125121  0.113170
16      2      7 -0.237605  0.091352  0.383976  0.072386  0.188102
17      2      8  0.320631 -0.003233 -0.051131  0.351749  0.159006
18      2      9 -0.028005 -0.005486  0.165539  0.231034  0.247790
19      2     10  0.283587 -0.026802  0.214904  0.208082  0.156947
20      3      1  0.294411 -0.137593  0.532814  0.073266  0.163069
21      3      2  0.054194  0.009029  0.398642  0.066362  0.012949
22      3      3 -0.211975  0.061155  0.181543  0.298219  0.033976
23      3      4  0.181339  0.146508  0.197321  0.221296  0.091367
24      3      5  0.196264 -0.055553  0.017934  0.118048  0.347331
25      3      6  0.368710 -0.084265  0.002103  0.227888  0.192013
26      3      7  0.170501 -0.105172  0.299640  0.243905  0.230138
27      3      8 -0.139135  0.000139  0.344663  0.404015  0.060641
28      3      9  0.184399  0.035735  0.321902  0.241217  0.184259
29      3     10  0.069735 -0.066923  0.236995  0.172572  0.304549
30      4      1  0.374373 -0.016168  0.174535  0.275058  0.241863
31      4      2  0.250820  0.063276 -0.047881  0.086867  0.088196
32      4      3  0.082953  0.053522  0.422896  0.221612  0.058314
33      4      4  0.524598  0.025327 -0.284130 -0.048987 -0.121796
34      4      5  0.338507  0.076063  0.034768  0.173972  0.038767
35      4      6  0.341740 -0.028285  0.002737  0.391661 -0.019301
36      4      7  0.456138  0.006202 -0.119871  0.221815  0.125246
37      4      8  0.329043 -0.033471  0.140055  0.281044  0.029042
38      4      9  0.215832  0.146832  0.179676  0.346451  0.059647
39      4     10  0.341838  0.051738  0.044491  0.229678  0.000722